rabix/bunny

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLBindings.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/helper/CWLSchemaHelper.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/Draft2Bindings.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/helper/Draft2SchemaHelper.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/Draft3Bindings.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/helper/Draft3SchemaHelper.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBBindings.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/helper/SBSchemaHelper.java, rabix-bindings/src/main/java/org/rabix/bindings/Bindings.java, rabix-bindings/src/main/java/org/rabix/bindings/model/DirectoryValue.java, rabix-bindings/src/main/java/org/rabix/bindings/model/FileValue.java
Added three new methods for extracting/updating FileValue objects from raw input.
=> FileValue helpers

rabix-backend-local/config/core.properties, rabix-backend-local/src/main/java/org/rabix/backend/local/BackendCommandLine.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLTranslator.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/Draft2Translator.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/Draft3Translator.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBTranslator.java, rabix-bindings/src/main/java/org/rabix/bindings/BindingsFactory.java
- introduce to Avro transformation from data type
- introduce hard links
=> Develop -> Master

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLCommandLineTool.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLExpressionTool.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLJobApp.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLPythonTool.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLWorkflow.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2CommandLineTool.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2ExpressionTool.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2JobApp.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2PythonTool.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2Workflow.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3CommandLineTool.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3ExpressionTool.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3JobApp.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3PythonTool.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3Workflow.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBCommandLineTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBExpressionTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBJobApp.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBPythonTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBWorkflow.java
Removed all String properties from specific app implementations. Modified getters to fetch those values from raw map that already exists in base Application class.
=> Using raw map to store all String properties of apps

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/helper/CWLSchemaHelper.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/helper/Draft2SchemaHelper.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/helper/Draft3SchemaHelper.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/helper/SBSchemaHelper.java, rabix-bindings/src/main/java/org/rabix/bindings/model/DataType.java
We're still missing proper validation against ENUM DataType (for now, every String value will pass validation). Still, this should unblock some folks that are waiting for enum support.
=> Added ENUM DataType

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLStepInputs.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3StepInputs.java
=> serializable

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLTranslator.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/Draft2Translator.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/Draft3Translator.java, rabix-bindings/src/main/java/org/rabix/bindings/helper/DAGValidationHelper.java
https://github.com/rabix/bunny/issues/95
=> Detection of workflows without links to any output port.

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/service/impl/CWLGlobServiceImpl.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/Draft2Processor.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/Draft3Processor.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBProcessor.java
=> Fix for issue 150.

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLCommandLineBuilder.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLCommandLineTool.java, rabix-common/src/main/java/org/rabix/common/helper/EncodingHelper.java
=> Shell quoting fixes

rabix-executor/src/main/java/org/rabix/executor/pathmapper/local/LocalPathMapper.java
Resolves #151 
See comments to #151
=> Fix issue with Windows paths

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLCommandLineBuilder.java
Related to https://github.com/rabix/bunny/issues/193
=> Check if there’s an inputBinding element in schema

rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java, rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/OutputEventHandler.java
Fixes the case where root job complete event is triggered before root job partially complete event
=> Race condition fix

rabix-engine/src/main/java/org/rabix/engine/service/impl/BackendServiceImpl.java, rabix-executor-rest/config/core.properties, rabix-executor-rest/src/main/java/org/rabix/executor/rest/ServerBuilder.java, rabix-transport/src/main/java/org/rabix/transport/backend/impl/BackendRabbitMQ.java
Fixed the issue of all heartbeats using the same exchange and routing key independent of the executor that sent them.
=> Now uses the same exchange but different routing keys.

rabix-backend-local/config/core.properties, rabix-backend-local/src/main/java/org/rabix/backend/local/BackendCommandLine.java, rabix-engine-rest/config/core.properties, rabix-engine/src/main/java/org/rabix/engine/EngineModule.java, rabix-engine/src/main/java/org/rabix/engine/lru/app/AppCache.java, rabix-engine/src/main/java/org/rabix/engine/lru/dag/DAGCache.java, rabix-engine/src/main/java/org/rabix/engine/processor/impl/MultiEventProcessorImpl.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/CacheServiceImpl.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/JobServiceImpl.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/SchedulerServiceImpl.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/StoreCleanupServiceImpl.java, rabix-engine/src/main/java/org/rabix/engine/stub/impl/BackendStubActiveMQ.java, rabix-engine/src/main/java/org/rabix/engine/stub/impl/BackendStubLocal.java, rabix-engine/src/main/java/org/rabix/engine/stub/impl/BackendStubRabbitMQ.java, rabix-executor-rest/config/core.properties, rabix-executor/src/main/java/org/rabix/executor/ExecutorModule.java, rabix-executor/src/main/java/org/rabix/executor/config/DockerConfigation.java, rabix-executor/src/main/java/org/rabix/executor/config/FileConfiguration.java, rabix-executor/src/main/java/org/rabix/executor/service/impl/CacheServiceImpl.java, rabix-tes-command-line/config/core.properties
Removed unused properties. 
Renamed most bunny.* and rabix.* properties to:
- backend.* for backend related properties
- engine.* for engine related properties
=> Reogranized properties.

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLCommandLineBuilder.java
Fix for https://github.com/rabix/bunny/issues/218
=> Fixes the binding check to work with lists instead of only with maps

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/helper/CWLFileValueHelper.java
Directories in secondary files have type "File" instead of "Directory"
=> Set the type of a secondary file correctly

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/CWLExpressionResolver.java
=> removed apparently unneeded peace of code that caused a bug

rabix-executor/pom.xml, rabix-executor/src/main/java/org/rabix/executor/container/impl/DockerContainerHandler.java
=> fix running images with entrypoint

rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBProcessor.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/processor/callback/SBInputSecondaryFilesProcessor.java
Missing input secondary files processor
=> SbInputSecondaryFilesProcessor

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/resolver/CWLDocumentResolver.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/resolver/Draft3DocumentResolver.java, rabix-cli/src/main/java/org/rabix/cli/BackendCommandLine.java
Related to: https://github.com/rabix/bunny/issues/291
=> Removes exception thrown for $schemas

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLRequirementProvider.java
Added recursive secondaryFiles staging and allowed secondaryFiles to be defined as a single expression as well as a list of expressions.
relates to https://github.com/rabix/bunny/issues/297 and https://github.com/rabix/bunny/issues/296
=> Minor secondary files fixes

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/resolver/CWLDocumentResolver.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/resolver/Draft2DocumentResolver.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/resolver/Draft3DocumentResolver.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/resolver/SBDocumentResolver.java
Prevents data maiming in case of embedded wfs
=> Better data uri base extraction

rabix-engine-store-postgres/src/main/java/org/rabix/engine/store/postgres/jdbi/impl/JDBIBackendRepository.java, rabix-engine-store-postgres/src/main/java/org/rabix/engine/store/postgres/jdbi/impl/JDBIEventRepository.java
Ran into some issues when running bunny with postgres
=> Typo and event deserialization fix

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java
Added support for lists; changed to append always if not expression; added extension and basename values to resolver
Also some minor refactors in the cwlprocessor class with util methods
=> Changed the way secondary files are resolved

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLEmbeddedApp.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLJobApp.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2EmbeddedApp.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/bean/Draft2JobApp.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3EmbeddedApp.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/bean/Draft3JobApp.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBEmbeddedApp.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBJobApp.java, rabix-bindings/src/main/java/org/rabix/bindings/model/Application.java, rabix-common/src/main/java/org/rabix/common/helper/JSONHelper.java, rabix-engine/src/main/java/org/rabix/engine/JobHelper.java, rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/AppServiceImpl.java, rabix-engine/src/test/java/org/rabix/engine/test/TestApp.java
Fixes problems with embedded apps of different cwl versions.
=> More consistent serialization of apps

rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBJobProcessor.java
With child steps not overwriting parent hints
=> Hints processing for sbg:draft-2

rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBJobProcessor.java
=> Revert "Hints processing for sbg:draft-2"

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/processor/callback/CWLInputSecondaryFilesProcessor.java, rabix-bindings/src/main/java/org/rabix/bindings/model/Application.java, rabix-engine-store-postgres/src/main/java/org/rabix/engine/store/postgres/jdbi/impl/JDBIEventRepository.java, rabix-engine-store/src/main/java/org/rabix/engine/store/memory/impl/InMemoryEventRepository.java, rabix-engine-store/src/main/java/org/rabix/engine/store/model/EventRecord.java, rabix-engine-store/src/main/java/org/rabix/engine/store/repository/EventRepository.java, rabix-engine/src/main/java/org/rabix/engine/event/Event.java, rabix-engine/src/main/java/org/rabix/engine/event/impl/ContextStatusEvent.java, rabix-engine/src/main/java/org/rabix/engine/event/impl/InitEvent.java, rabix-engine/src/main/java/org/rabix/engine/event/impl/InputUpdateEvent.java, rabix-engine/src/main/java/org/rabix/engine/event/impl/JobStatusEvent.java, rabix-engine/src/main/java/org/rabix/engine/event/impl/OutputUpdateEvent.java, rabix-engine/src/main/java/org/rabix/engine/processor/impl/EventProcessorImpl.java, rabix-engine/src/main/resources/org/rabix/engine/jdbi/dbinit.sql
Some minor changes required for platform compatibility
=> Platform changes

rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/SBJobProcessor.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBCommandLineTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBEmbeddedApp.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBExpressionTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBJobApp.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBPythonTool.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBStep.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/bean/SBWorkflow.java, rabix-executor/src/main/java/org/rabix/executor/service/impl/CacheServiceImpl.java
Added a hints cascade that goes workflow -> job -> app
=> Hints cascade

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/CWLExpressionResolver.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/javascript/CWLExpressionJavascriptResolver.java
bug fix for escaped characters inside of regex strings
=> Simpler js interpolation and resolution,

rabix-bindings/src/main/java/org/rabix/bindings/helper/FileValueHelper.java, rabix-bindings/src/main/java/org/rabix/bindings/model/DataType.java
Merge commit '8611975d60e4e03a3fa8a4fb57b992f36f039747' into task/empty-array-validation
=> Allow empty array as valid input

rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/processor/CWLPortProcessor.java, rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/processor/Draft2PortProcessor.java, rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/processor/Draft3PortProcessor.java, rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/processor/SBPortProcessor.java, rabix-engine/src/main/java/org/rabix/engine/JobHelper.java, rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java, rabix-engine/src/main/java/org/rabix/engine/service/impl/JobRecordServiceImpl.java, rabix-executor/src/main/java/org/rabix/executor/handler/impl/JobHandlerImpl.java
Input port logs are currently unnecessary
=> Less debug logs

rabix-backend-tes/src/main/java/org/rabix/backend/tes/TESModule.java, rabix-backend-tes/src/main/java/org/rabix/backend/tes/client/TESHttpClient.java, rabix-backend-tes/src/main/java/org/rabix/backend/tes/config/TESConfig.java, rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESWorkerServiceImpl.java, rabix-backend-tes/src/main/resources/META-INF/services/java.nio.file.spi.FileSystemProvider, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLRequirementProvider.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/helper/CWLFileValueHelper.java, rabix-cli/config/core.properties
closes #417 
closes #418 
closes #420 
closes #422
=> TES and S3 bugfixes

pom.xml, rabix-backend-lsf/pom.xml, rabix-backend-lsf/src/main/java/org/rabix/backend/lsf/service/LSFWorkerServiceImpl.java, rabix-cli/pom.xml, rabix-engine-rest/pom.xml
Fixed most conformance tests when running with LSF
=> Fixed LSF for conformance tests

rabix-backend-tes/pom.xml, rabix-backend-tes/src/main/java/org/rabix/backend/tes/TESModule.java, rabix-backend-tes/src/main/java/org/rabix/backend/tes/config/TESConfig.java, rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/helper/CWLFileValueHelper.java, rabix-cli/config/core.properties
This PR allows users to configure multiple S3 providers. 
Note that I had to fork the S3 NIO library and make a few modifications.
=> Support for multiple S3 providers

rabix-cli/config/core.properties, rabix-cli/src/main/java/org/rabix/cli/BackendCommandLine.java
Sorry I forgot to make these changes in the previous PR.
=> Fix flag to config mapping for TES backend
