rabix/bunny

- rabix-backend-local/bin/rabix
When you link the shell script that runs the executor, it does not resolve the symlink and tries to run `/usr/bin/local/lib/rabix-backend-local.jar`.
This fixes that behaviour, so the jar file will searched for in the folder where the rabix script is located, not where its symlink is found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rabix/bunny/50)
> Make rabix symlink-able

- rabix-backend-local/config/logback-verbose.xml
- rabix-backend-local/config/logback.xml
- rabix-common/src/main/java/org/rabix/common/logging/VerboseLogger.java
- rabix-tes-command-line/config/logback-verbose.xml
- rabix-tes-command-line/config/logback.xml
VerboseLogger now logs everything, regardless of -v param
Every other logger has a default level of WARN. Specifying -v option will change it to DEBUG, and add some more details in the log line (Line in the code where error occurred, etc.)
> Improved logging configurations

- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/OutputEventHandler.java
Prevents the accidental triggering of an output update event on a sepp by a previous step.
Relates to the case when a step’s input port and output port have the same name, described in: https://github.com/rabix/bunny/issues/117
> Fix for ports with the same name issue #117

- rabix-executor/src/main/java/org/rabix/executor/config/impl/DefaultStorageConfiguration.java
Replaces all non-alphanumeric characters in step ids with '_'
Relates to errors that happen when a folder to be created contains > < or similar chars
https://github.com/rabix/bunny/issues/149
> Wider string sanitization for folder naming

- rabix-engine-rest/src/main/java/org/rabix/engine/rest/ServerBuilder.java
- rabix-engine/src/main/java/org/rabix/engine/processor/EventProcessor.java
- rabix-engine/src/main/java/org/rabix/engine/processor/handler/HandlerFactory.java
- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/OutputEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/processor/impl/EventProcessorImpl.java
- rabix-engine/src/main/java/org/rabix/engine/processor/impl/MultiEventProcessorImpl.java
- rabix-engine/src/main/java/org/rabix/engine/service/JobService.java
- rabix-engine/src/main/java/org/rabix/engine/service/impl/JobServiceImpl.java
- rabix-engine/src/test/java/org/rabix/engine/EngineModuleTest.java
All status events now happen through JobService, NoOpEngineStatusCallback is used instead of EngineStatusCallbackImpl.
> Engine status callback change

- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/processor/impl/EventProcessorImpl.java
- rabix-engine/src/main/java/org/rabix/engine/service/impl/JobServiceImpl.java
Events for a job failing were never updated to a status different from UNPROCESSED so they were always skipped on every engine start
Also Removed Duplicate code for root job failed
Also Added messages to event sending
> Deletes events from an aborted or failed context

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLEmbeddedApp.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/CWLInputPort.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/json/CWLInputPortsDeserializer.java
Should address #211 
I only fixed this in the CWL 1.0 bindings.  I wanted to get feedback on my approach before doing anything else.
> Discover secondary files for inputs (#211)

- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/OutputEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/ScatterHandler.java
Stops the wrapping of empty lists and premature exit from the scatter port method if empty list is detected.
Relates to https://github.com/rabix/bunny/issues/246
> A change to the empty list scatter handling

- rabix-engine/src/main/java/org/rabix/engine/service/impl/BootstrapServiceImpl.java
Crashes when using postgres because backendService.scanEmbedded() creates another transaction to save backend to db
> Removed a transaction inside a transaction

- rabix-common/src/main/java/org/rabix/common/helper/EncodingHelper.java
@AleksandarPetrovicSBG , @simonovic86 cwltool puts empty quotation marks when provided empty string, as we concluded is the most meaningful solution, so with this fix, bunny has the same behavior.
> handling empty strings when quoting

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/CWLProcessor.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/CWLExpressionResolver.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/resolver/CWLDocumentResolver.java
- rabix-bindings/src/main/java/org/rabix/bindings/CommandLine.java
Explicitly added .length to expressions and namespace resolution at output generation. Removed the removal of multiple spaces from commandlines.
> Conformance tests fixes

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/resolver/CWLDocumentResolver.java
Instead of always using the root one.
Relates to https://github.com/rabix/bunny/issues/281
TODO: previous drafts
> Creates a relative path for traversal of embedded workflows

- rabix-executor/src/main/java/org/rabix/executor/handler/impl/JobHandlerImpl.java
- rabix-executor/src/main/java/org/rabix/executor/service/impl/CacheServiceImpl.java
Caching now detects changes in original inputs including file contents.
Any change will trigger a dry run of a given job.
If a slight change in inputs alter a part of the workflow, cache will continue to server unaltered parts.
> Improved caching capabilities.

- README.md
The `wget` command downloaded the _tar_ file with _filename_ depending on the redirect, therefore the subsequent _untar_ fails. By specifying the `-O` flag we can force a filename, so that the _untar_ command works.
> update download release command

- rabix-bindings-draft2/src/main/java/org/rabix/bindings/draft2/helper/Draft2FileValueHelper.java
- rabix-bindings-draft3/src/main/java/org/rabix/bindings/draft3/helper/Draft3FileValueHelper.java
- rabix-bindings-sb/src/main/java/org/rabix/bindings/sb/helper/SBFileValueHelper.java
Sometimes, we need to use dirname value in older drafts. This should populate dirname inside FileValue for Draft2, SB and Draft3, same as it's being done for CWL.
> Added support for dirname field in FileValue for older drafts.

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/service/impl/CWLGlobServiceImpl.java
CWLGlobServiceImpl was matching only filenames while traversing the file tree. Instead, whole path should have been matched against the given glob pattern.
However, due to complete path being absolute, classical glob matching patterns do not work. Instead, path starting from working directory and ending with filename should be used for matching. E.g.
```
Path: /home/halil/cwl-tests/simple2-2017-06-27-174426.530/root/header_step/insider/file1_header 
Work: /home/halil/cwl-tests/simple2-2017-06-27-174426.530/root/header_step/
Path to use for matching: insider/file1_header
```
This matches a glob pattern like ```insider/*_header```
> Updated pull request for glob subdirectory matching

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/CWLExpressionResolver.java
Resolver didn't check whether the processed line is commented out or not. This caused a problem when a comment like following occurred in the javascript code
```
// This should'nt affect code
```
Resolver thinks there is a quotation started in ```should'nt``` but it has no matching end.
Edit: Forgot to add the mention to the issue.
> Fixes #274, commented javascript lines caused error in resolver.

- rabix-common/src/main/java/org/rabix/common/helper/JSONHelper.java
Everything in a deserialized map shouldn’t be skipped if it comes after a null value
Relates to https://github.com/rabix/bunny/issues/322
> Deserializing maps with null values

- rabix-engine/src/main/java/org/rabix/engine/service/SchedulerService.java
- rabix-engine/src/main/java/org/rabix/engine/service/impl/SchedulerServiceImpl.java
Removed JobBackendAssignment and switched to using JobEntity as before. Also, the assign method is now accessed through IoC instead of always the local one.
> Simpler assignment of jobs with the createdBy node name retained

- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/InitEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/processor/handler/impl/JobStatusEventHandler.java
- rabix-engine/src/main/java/org/rabix/engine/service/impl/JobRecordServiceImpl.java
Fix for skipping steps when there are multiple incoming values for one of the root apps' output port
> Fix for skipping steps

- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/CWLExpressionResolver.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression/javascript/CWLExpressionJavascriptResolver.java
Fix for comments and strings breaking the expression extraction. Also added a clearer error message containing the expression that caused it.
> Fix for javascript interpolation

- .dockerignore
- Dockerfile
Minimal Dockerfile for rabix-cli.
Uses the multistage build process available from Docker 17.05 to keep the image size small.
https://docs.docker.com/engine/userguide/eng-image/multistage-build/
> Multistage Dockerfile

- rabix-executor/src/main/java/org/rabix/executor/container/impl/DockerContainerHandler.java
- rabix-executor/src/main/java/org/rabix/executor/service/impl/FilePermissionServiceImpl.java
Change for https://github.com/rabix/bunny/issues/371 where start container both started the container and failed due to time out, making the method retry. Now every retry of the start command checks if it actually completed before retrying.
> Docker start container smarter retry

- rabix-backend-tes/src/main/java/org/rabix/backend/tes/TESModule.java
- rabix-backend-tes/src/main/java/org/rabix/backend/tes/config/TESConfig.java
- rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESStorageServiceImpl.java
- rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESWorkerServiceImpl.java
- rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/bean/resource/requirement/CWLResourceRequirement.java
- rabix-cli/config/core.properties
I messed up a few things in the last few commits of my previous PR.
> TES backend bugfix
